# Generated by Django 5.2.6 on 2025-10-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_conversation_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAdminFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_save_conversation', 'Puede guardar conversaciones en n8n')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
